ZOOKEEPER-4641: GH CI fails with error: implicit declaration of function FIPS_mode
Modifications:
- remove the block, as it is used only for debug

More details here:
https://issues.apache.org/jira/browse/ZOOKEEPER-4641

Author: Enrico Olivelli <enrico.olivelli@datastax.com>

Reviewers: Andor Molnar <andor@apache.org>, Chris Nauroth <cnauroth@apache.org>, Mate Szalay-Beko <symat@apache.org>

Closes #1951 from eolivelli/fix/ZOOKEEPER-4641